---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: maven:3-jdk-8
    commands:
      - mvn clear package -DskipTests=true