kind: pipeline
name: default

workspace:
  base: /go
#  path: src/github.com/cuisongliu/githubio

steps:
  - name: submodules
    image: docker:git
    commands:
      - git clone --recursive https://github.com/15223706694/gogoTest.git
  - name: build-hugo
    image: golang:1.13
    settings:
      username:  15223706694
      password:  flx231224..
      
